CREATE TABLE VENDORS (
    VENDOR_ID NUMBER PRIMARY KEY,
    VENDOR_NAME VARCHAR2(100) NOT NULL,
    CONTACT_PERSON VARCHAR2(100),
    PHONE_NUMBER VARCHAR2(15),
    EMAIL VARCHAR2(100),
    CITY VARCHAR2(50)
);
