CREATE TABLE VENDORS (
    VENDOR_ID NUMBER PRIMARY KEY,
    VENDOR_NAME VARCHAR2(100) NOT NULL,
    CONTACT_PERSON VARCHAR2(100),
    PHONE_NUMBER VARCHAR2(15),
    EMAIL VARCHAR2(100),
    CITY VARCHAR2(50)
);
CREATE TABLE USERS (
    USER_ID NUMBER PRIMARY KEY,
    USER_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE,
    ROLE VARCHAR2(30),
    PHONE_NUMBER VARCHAR2(15)
);
