CREATE TABLE VENDORS (
    VENDOR_ID NUMBER PRIMARY KEY,
    VENDOR_NAME VARCHAR2(100) NOT NULL,
    CONTACT_PERSON VARCHAR2(100),
    PHONE_NUMBER VARCHAR2(15),
    EMAIL VARCHAR2(100),
    CITY VARCHAR2(50)
);
CREATE TABLE USERS (
    USER_ID NUMBER PRIMARY KEY,
    USER_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE,
    ROLE VARCHAR2(30),
    PHONE_NUMBER VARCHAR2(15)
);
CREATE TABLE PURCHASE_REQUEST (
    PR_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER,
    REQUEST_DATE DATE,
    STATUS VARCHAR2(20),
    TOTAL_AMOUNT NUMBER(10,2),
    CONSTRAINT FK_PR_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
);
CREATE TABLE PURCHASE_REQUEST_ITEMS (
    PR_ITEM_ID NUMBER PRIMARY KEY,
    PR_ID NUMBER,
    PRODUCT_ID NUMBER,
    QUANTITY NUMBER,
    UNIT_PRICE NUMBER(10,2),
    CONSTRAINT FK_PRI_PR
        FOREIGN KEY (PR_ID)
        REFERENCES PURCHASE_REQUEST(PR_ID),
    CONSTRAINT FK_PRI_PRODUCT
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCTS(PRODUCT_ID)
);
