CREATE OR REPLACE FUNCTION GET_PRODUCT_STOCK
(
    P_PRODUCT_ID IN NUMBER
)
RETURN NUMBER
IS
    V_STOCK NUMBER;
BEGIN
    SELECT STOCK_QTY
    INTO V_STOCK
    FROM PRODUCTS
    WHERE PRODUCT_ID = P_PRODUCT_ID;

    RETURN V_STOCK;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
END;
/
